language: objective-c
 
os: osx 
osx_image: xcode8
xcode_sdk: iphonesimulator10.0

install:
    - export LANG=en_US.UTF-8
    - brew update
    - open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID "2FF98FA6-99CC-4DE4-950B-A31BA28C6274"
    - nvm install 4
    - gem install cocoapods
    - npm install -g grunt-cli
    - npm install -g nativescript --ignore-scripts
    - tns usage-reporting disable
    - tns error-reporting disable
    - npm install
    
script:
    - grunt build
    - cd sample
    - npm install
    - tns test ios --emulator --justlaunch
    - cd ..
